### ISSUE TITLE
Add documentation about DummyController

### ISSUE THREAD

**Issue by nicodemuz** [web-auth/doc#25]
When trying to implement registration, I encoutered the following issue:

```This method should never be called.```

![image](https://github.com/web-auth/doc/assets/1620454/b7fa79e0-9940-4552-b89e-1d4a48c2e77e)

What is the correct way to fix this issue? I did not see this controller overridden in the Symfony demo application.

**Comment by Spomky** [comment]
Hi @nicodemuz,

🤔 It looks like the listener is not called.
Are you sure of the following:
* the [registration is enabled](https://github.com/web-auth/symfony-demo/blob/production/config/packages/security.yaml#L19-L20) in the security config file? 
* the route is [behind the `webauthn` authenticator](https://github.com/web-auth/symfony-demo/blob/production/config/packages/security.yaml#L16)?

**Comment by nicodemuz** [comment]
I was actually trying to add it to a page where an already registered user can add a new passkey, and then I found separate documentation that worked for this. Somehow I managed to fix it, but I'm not sure which change fixed it. I will try to implement registration page soon, again! I will close this for now! :)

**Comment by Spomky** [comment]
OK I misunderstood the use case.
To allow registered users to add another authenticator, there are a few configuration line to add:

* In the bundle configuration file, enable the `controllers` feature. It works as the firewall, but the user is supposed to be known. See [here as an example](https://github.com/web-auth/symfony-demo/blob/production/config/packages/webauthn.yaml#L33-L39). Note the controller key `additional_authenticator` in the example for the last step.
* Make sure the routes are [behind a firewall](https://github.com/web-auth/symfony-demo/blob/production/config/packages/security.yaml#L46).
* You can then have [a button in a template](https://github.com/web-auth/symfony-demo/blob/production/templates/authenticators/index.html.twig#L40-L52) for user interaction. Routes are automatically created `webauthn.controller.creation.request.additional_authenticator` and `webauthn.controller.creation.response.additional_authenticator` (`additional_authenticator` is the key in the first step)

**Comment by 7system7** [comment]
Hello,

I got the same error and I could not figure out all day what is the problem. 🫠 I set up this bundle at least 100 different way but the `/register` entry point always run into the DummyController w/ this message "This method should never be called." w/o **any real error message.** Sadly the Xdebug did not help, because the stack trace is so small - actually the entry point does not work, just run into that Controller.

I have an Api platform and I set up this bundle as the documentation says. This is my security.yaml

```yaml
    main:
      two_factor:
        prepare_on_login: true
        prepare_on_access_denied: true
        auth_code_parameter_name: authCode
        post_only: true
      json_login:
        check_path: '/api/authentication_token'
        provider: yellowcube_user_provider
        username_path: id
        password_path: password
      pattern: '^/api/authentication_token'
      custom_authenticators:
        - App\Security\LoginAuthenticator
      webauthn:
        registration:
          enabled: true
        authentication:
          enabled: true
```

and I presume, the access_control settings are OK.

```yaml
  access_control:
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: PUBLIC_ACCESS }                     # Allows accessing the Swagger UI
    - { path: ^/docs, roles: PUBLIC_ACCESS }                    # Allows accessing the Swagger UI
    - { path: ^/currency, roles: PUBLIC_ACCESS }                # Allows accessing the currency information
    - { path: ^/login,  roles: PUBLIC_ACCESS, requires_channel: 'https' }
    - { path: ^/register,  roles: PUBLIC_ACCESS, requires_channel: 'https' }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

I set up my
 - `WebauthnCredential` the same as the docs
 - `WebauthnCredentialRepository` the same as the docs
 - `WebauthnCredentialUserRepository` where I implemented the `PublicKeyCredentialUserEntityRepositoryInterface,` the `CanGenerateUserEntity` & the `CanRegisterUserEntity`
 - aaaand I migrated my database.

and I have this configuration:

```yaml
webauthn:
  credential_repository: 'App\Repository\User\WebauthnCredentialRepository'
  user_repository: 'App\Repository\User\WebauthnCredentialUserRepository'
  creation_profiles:
    default:
      rp:
        name: '%env(RELYING_PARTY_NAME)%'
        id: '%env(RELYING_PARTY_ID)%'
  request_profiles:
    default:
      rp_id: '%env(RELYING_PARTY_ID)%'
```

I run out of my all ideas what is the problem. If you have any suggestion. please do not hesitate to share w/ me. 🙏🏻 I really thinking on that, I will implement a custom entry point to handle the situation. :disappointed:

**Comment by Spomky** [comment]
Hi,

As mentioned earlier in the discussion, the route shall be [behind the webauthn authenticator](https://github.com/web-auth/symfony-demo/blob/production/config/packages/security.yaml#L16).

Your firewall pattern is `^/api/authentication_token`, but you are using the default paths that are `^/login` and `^/register`. You should change the pattern or define paths that match the pattern.

**Comment by 7system7** [comment]
Hi,

Omg... I did not understood clearly what did you mean "before pattern". :smile: I changed the pattern to `^/` and it just works. Thank you so much. I'd say I should have a coffee, but I think I'd rather get some sleep. :sleeping_bed:

**Comment by 7system7** [comment]
Hello,

Actually, I would use this bundle just like @nicodemuz. I tried to create the classes what you mentioned here

> OK I misunderstood the use case.
To allow registered users to add another authenticator, there are a few configuration line to add:
>    In the bundle configuration file, enable the controllers feature. It works as the firewall, but the user is supposed to be known. See [here as an example](https://github.com/web-auth/symfony-demo/blob/production/config/packages/webauthn.yaml#L33-L39). Note the controller key additional_authenticator in the example for the last step.
>    Make sure the routes are [behind a firewall](https://github.com/web-auth/symfony-demo/blob/production/config/packages/security.yaml#L46).
>    You can then have [a button in a template](https://github.com/web-auth/symfony-demo/blob/production/templates/authenticators/index.html.twig#L40-L52) for user interaction. Routes are automatically created webauthn.controller.creation.request.additional_authenticator and webauthn.controller.creation.response.additional_authenticator (additional_authenticator is the key in the first step)

When I call the `/profile/authenticators/add/options`, I got 401 error. (Because it is behind the security firewall.) If I do not use this behind a firewall I figured out that, somehow the `CurrentUserEntityGuesserManager` cannot recognize the current session. This [API](https://api-platform.com/) is communicating through [JWT](https://api-platform.com/docs/core/jwt/#jwt-authentication) based authentication through the Authorization header and a Bearer token. Even if I pass this header, the `TokenStorageInterface` tells me that, the `->getToken()?->getUser()` is null.

Do you have any idea what have I miss again? Thank you in advance!

**Comment by Spomky** [comment]
Hi @7system7,

I am sorry if the documentation is not clear enough for this spefici points.

The controllers are used for 2 different purposes:

1. The authentication or the registration of anonymous users
2. The registration of a new authenticator by a fully authenticated user

For the use case 1., the paths shall be available for anonymous users and everything is configured in the `security` file.

Hereafter an example of configuration:

```yaml
#config/packages/security.yaml
security:
    main:
      pattern: '^/api'
      custom_authenticators:
        - App\Security\LoginAuthenticator
      webauthn:
        registration:
          enabled: true
          routes:
            options_path: '/api/login/options'
            result_path: '/api/login/result'
        authentication:
          enabled: true
          routes:
            options_path: '/api/register/options'
            result_path: '/api/register/result'
    access_control:
        - { path: ^/api/login,  roles: PUBLIC_ACCESS, requires_channel: 'https'}
        - { path: ^/api/register,  roles: PUBLIC_ACCESS, requires_channel: 'https'}
```

For the use case 2., the paths shall be protected behind. The configuration is done in the package config file and access to those routes is defined in the security file.
It is important that the controller paths are behind the firewall (here I chose `^/api`).

Hereafter an example of configuration:

```yaml
config/packages/webauthn.yaml

webauthn:
    controllers:
        enabled: true
        creation:
            from_user_account:
                options_path: '/api/profile/security/devices/add/options'
                result_path: '/api/profile/security/devices/add'
                user_entity_guesser: Webauthn\Bundle\Security\Guesser\CurrentUserEntityGuesser
                hide_existing_credentials: false

#config/packages/security.yaml
security:
    access_control:
        - { path: ^/api/profile,  roles: IS_AUTHENTICATED_FULLY , requires_channel: 'https'}
```

----

**Note on the configuration you shared in https://github.com/web-auth/doc/issues/25#issuecomment-2403318755**

I am not sure it is a good idea to mix stateless authentication with JWT and stateful auth (2FA, LoginAuthenticator and Webauthn).
If is preferrable to split.
* API (/api): stateless with JWT
* Other sections such as the documentation or a dashboard: stateful
